Repository kaiwilens/Python_text-based_game, pull requests merged in 2021-04, with the labels that each got.

#47 Added leveling up attributes and created playable characters
  .idea/workspace.xml
  Character_Tests.py
  Characters.py
  Playable_Characters.py
  main.py
Labels: enhancement, python functions

#52 Updated the README file and fixed the title screen operating system problem
  README.md
  Title_Screen.py
Labels: python functions

#62 Battle sequence improvements
  Battle_Sequence.py
  Character_Descriptions.py
  Character_Tests.py
  Playable_Characters.py
  Story.py
Labels: duplicate, enhancement
